### ISSUE TITLE
Crash when trying to view Open Journal System

### ISSUE THREAD

**Issue by gandalfar** [hbz/oerworldmap#1972]
Steps to reproduce:

1. Visit https://oerworldmap.org/resource/urn:uuid:6d50094b-eeb7-49bd-937c-f5533afffc4e
(or search for Open Journal System and click on the link)

**Comment by dr0i** [comment]
Is this connected to https://github.com/hbz/oerworldmap/issues/1961 ?

**Comment by gandalfar** [comment]
I think it's a different issue as I don't see a reason why it would be deleted.

**Comment by gandalfar** [comment]
I investigated this a bit more and it's not happening on my dev version. I'm using a recent dataset from production (Sep 2020).

It seems to be a backend issue, since the crash also happens when trying to access JSON file: https://oerworldmap.org/resource/urn:uuid:6d50094b-eeb7-49bd-937c-f5533afffc4e.json

**Comment by gandalfar** [comment]
Another case:

> https://oerworldmap.org/resource/urn:uuid:6890a7aa-a383-4813-88d0-acefdfe7a21a

**Comment by gandalfar** [comment]
@dr0i can you look into server logs what the server side exception is, when clicking on this link: https://oerworldmap.org/resource/urn:uuid:6d50094b-eeb7-49bd-937c-f5533afffc4e.json ? 

I assume crash logs are not available publicly.

**Comment by dr0i** [comment]
It's this:

> 2020-10-01 15:50:26,224 [ERROR] from application in application-akka.actor.default-dispatcher-438902 - 
! @7habm5a7b - Internal server error, for (GET) [/resource/urn:uuid:6d50094b-eeb7-49bd-937c-f5533afffc4e.json] ->
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
